initial <- read.table("household_power_consumption.txt", header=TRUE, sep = ";", nrows= 10)
classes <- sapply(initial, class)
entire <- read.table("household_power_consumption.txt", header=TRUE, sep= ";", na.strings="?", colClasses = classes)
entire[,1] <- as.Date(entire[,1], format = "%d/%m/%Y")
sub <- subset(entire, Date == "2007-02-01" | Date == "2007-02-02")
daywithtime <- paste(sub[,1],sub[,2])
fixed_time <- strptime(daywithtime, format = "%Y-%m-%d %H:%M:%S",tz="")

par(mfcol= c(2,2), mar= c(4,4,2,2), oma= c(0,0,0,0))
firstplot <- plot(fixed_time, sub[,3], sub= NULL, xlab= " ", ylab = "Global Active Power (kilowatts)", type = "l", cex= 0.5)
secondplot <- plot(fixed_time, sub[,7], sub= NULL, xlab= " ", ylab = "Energy sub metering", type = "l")
lines(fixed_time, sub[,8], col = "red")
lines(fixed_time, sub[,9], col = "blue")
legend("topright",pch= NA, col = c("black", "red", "blue"), legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), 
       lwd=1, bty= "n", inset= .1, cex = .75)
thirdplot <- thirdplot <- plot(fixed_time, sub[,5], sub= NULL, xlab= "datetime ", ylab = "Voltage", type = "l", lwd=0.75)
fourthplot <- plot(fixed_time, sub[,4], sub= NULL, xlab= "datetime ", ylab = "Global_reactive_power", type = "l", lwd=0.75)
dev.copy(png, file= "plot4.png", width = 480, height = 480)
dev.off()
