initial <- read.table("household_power_consumption.txt", header=TRUE, sep = ";", nrows= 10)
classes <- sapply(initial, class)
entire <- read.table("household_power_consumption.txt", header=TRUE, sep= ";", na.strings="?", colClasses = classes)
entire[,1] <- as.Date(entire[,1], format = "%d/%m/%Y")
sub <- subset(entire, Date == "2007-02-01" | Date == "2007-02-02")
firstplot <- hist(sub[,3], main = "Global Active Power", xlab= "Global Active Power (kilowatts)", col = "red")
dev.copy(png, file= "plot1.png", width = 480, height = 480)
dev.off()
