initial <- read.table("household_power_consumption.txt", header=TRUE, sep = ";", nrows= 10)
classes <- sapply(initial, class)
entire <- read.table("household_power_consumption.txt", header=TRUE, sep= ";", na.strings="?", colClasses = classes)
entire[,1] <- as.Date(entire[,1], format = "%d/%m/%Y")
sub <- subset(entire, Date == "2007-02-01" | Date == "2007-02-02")
daywithtime <- paste(sub$Date,sub$Time)
fixed_time <- strptime(daywithtime, format = "%Y-%m-%d %H:%M:%S",tz="")
secondplot <- plot(fixed_time, sub[,3], sub= NULL, xlab= " ", ylab = "Global Active Power (kilowatts)", type = "l")
dev.copy(png, file= "plot2.png", width = 480, height = 480)
dev.off()
